version: '3.8'

services:
  app:
    build: .
    ports:
      - "5555:5555"
    depends_on:
      - mongo
    environment:
      MONGODB_URL: "mongodb+srv://harshjhankda200988:comic20098@cluster1.2jbsuyz.mongodb.net"


  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
